---
apiVersion: v1
kind: Service
metadata:
  name: transaction-generator
  labels:
    app: office-space
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: office-space
    tier: transaction
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-generator
  labels:
    app: office-space
spec:
  selector:
    matchLabels:
      app: office-space 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: office-space
        tier: transaction
    spec:
      containers:
        - image: tg:latest
          imagePullPolicy: Never
          name: transaction-generator
          ports:
            - containerPort: 8080
